name: CI Workflow template
on:
  workflow_call:
  inputs:
    username:
      required: true
      type: string
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a hello world script
        run: echo Hello, ${{ inputs.username }}
