name: GitHub Reusable Workflow demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  call-workflow-A:
    uses: rutulpatel/gh-actions/.github/workflows/wt-ci.yml@main
    with:
      username: Rick

  call-workflow-B:
    uses: rutulpatel/gh-actions/.github/workflows/wt-ci.yml@main
    with:
      username: Morty
    